### ISSUE TITLE
[BUG] Feeds don't seem to automatically refresh since 1.19 upgrade

### ISSUE THREAD

**Issue by Jucgshu** [marienfressinaud/FreshRSS#4117]
**Describe the bug**
Since upgrade to 1.19, feeds don't seem to automatically refresh. I have to manually click the refresh button on the webpage.

**Expected behavior**
Feeds should refresh themselves.

**Environment information (please complete the following information):**
- OS: Docker 1:20.10, Docker-Compose 2.2.2
- FreshRSS version: 1.19, 1.19.1.

**Additional context**
Can't seem to find any relevant info in the logs.

**Comment by Frenzie** [comment]
What do you see if you try the command from your cron job manually?

Edit: sorry, overlooked the Docker. Not sure what the best way to debug cron & Docker is exactly.

**Comment by Jucgshu** [comment]
Not sure it's cron based but there you are:
```
root@c3d5b85ea593:/var/www/FreshRSS# crontab -l
no crontab for root
```

**Comment by Jucgshu** [comment]
I checked the actualize script which seems to work fine when I force it inside the container. I think you're right @Frenzie , probably something with the cron not working properly.

**Comment by thelazyoxymoron** [comment]
I'm also facing the same issue (docker). Manual refresh makes it work again, seems to be some error with cron installation. I restarted the container and got this in the logs:
```
"-":0: bad minute
errors in crontab file, can't install.
```

**Comment by Alkarex** [comment]
@thelazyoxymoron What Docker image are you using, more precisely?

**Comment by Alkarex** [comment]
Might be related to https://github.com/FreshRSS/FreshRSS/pull/3927

**Comment by Alkarex** [comment]
Please provide your `docker run` or docker-compose if possible

**Comment by Jucgshu** [comment]
Sure, there it is:
```
  freshrss:
    image: freshrss/freshrss
    container_name: freshrss
    environment:
      - user=${USER}
      - TZ=Europe/Paris
      - CRON_MIN = '*/20'
    volumes:
      - /opt/appdata/freshrss:/var/www/FreshRSS/data
    ports:
      - 8081:80
    restart: unless-stopped
```

**Comment by Alkarex** [comment]
@Jucgshu When I try your docker-compose, I get the following docker-compose error: `ERROR: environment variable name 'CRON_MIN ' may not contain whitespace.`

However, please try with this slightly modified version of your docker-compose:

```yml
version: "3"
services:
  freshrss:
    image: freshrss/freshrss
    container_name: freshrss
    environment:
      TZ: Europe/Paris
      CRON_MIN: '*/20'
    volumes:
      - /opt/appdata/freshrss:/var/www/FreshRSS/data
    ports:
      - 8081:80
    restart: unless-stopped
```

**Comment by Alkarex** [comment]
So either:

```yml
    environment:
      - TZ=Europe/Paris
      - CRON_MIN=*/20
```

or

```yml
    environment:
      TZ: Europe/Paris
      CRON_MIN: '*/20'
```

but not a mix of the two syntaxes: https://docs.docker.com/compose/compose-file/compose-file-v3/#environment

**Comment by Alkarex** [comment]
For the record, the wrong syntax ~~`CRON_MIN='*/20'`~~ sets the environment variable to `'*/20'` _with_ the quotes

**Comment by thelazyoxymoron** [comment]
I had the following in my `docker-compose`:

```
environment:
    - CRON_MIN='4,34'
```
which used to work fine till 1.19, but seeing your above response, changed the variable to `- CRON_MIN=4,34` which so far looks to have worked. I'm still curious though about how it used to work earlier. 

My docker-compose:
```
version: '3.8'
 
 services:
     freshrss:
         image: freshrss/freshrss
         container_name: freshrss
         restart: unless-stopped
         volumes:
             - freshrss-data:/var/www/FreshRSS/data
             - freshrss-extensions:/var/www/FreshRSS/extensions
         environment:
             - CRON_MIN='4,34'
             - TZ=Asia/Kolkata
         networks:
             - proxy-network
 
 volumes:
     freshrss-data:
         external: true
     freshrss-extensions:
         external: true
 
 networks:
     proxy-network:
         external: true
```
